maximum_user_length=37
minimum_user_length=3

maximum_password_length=37
minimum_password_length=4

password_mask="â€¢"

bypass_blacklist=["bypass_blacklist"]

ips=[
	"1\\.1\\.1\\.1",
	"8\\.8\\.8\\.8",
	"0\\.0\\.0\\.0",
	"1\\.1\\.2\\.2",
	"9\\.9\\.9\\.9",
	"149\\101\\100\\0",
	"149\\101\\101\\0",
	"149\\101\\102\\0",
	"149\\101\\103\\0",
	"149\\101\\118\\0\\",
	"149\\101\\164\\0\\",
	"149\\101\\216\\0\\",
	"149\\101\\229\\0\\",
	"149\\101\\242\\0\\",
	"153\\31\\0\\0\\",
	"153\\31\\128\\0\\",
	"153\\31\\192\\0\\",
	"155\\206\\0\\0\\",
"152\\120\\0\\0\\",
"150\\120\\0\\0\\",
"149\\101\\92\\0\\",
"149\\101\\83\\0\\",
"149\\101\\80\\0\\",
"149\\101\\72\\0\\",
"149\\101\\68\\0\\",
"149\\101\\57\\0\\",
"149\\101\\52\\0\\",
"149\\101\\50\\0\\",
"149\\101\\47\\0\\",
"149\\101\\45\\0\\",
"149\\101\\40\\0\\",
"149\\101\\32\\0\\",
"149\\101\\30\\0\\",
"149\\101\\29\\0\\",
"149\\101\\26\\0\\",
"149\\101\\25\\0\\",
"149\\101\\242\\0\\",
"149\\101\\229\\0\\",
"149\\101\\228\\0\\",
"149\\101\\226\\0\\",
"149\\101\\222\\0\\",
"149\\101\\22\\0\\",
"149\\101\\216\\0\\",
"149\\101\\21\\0\\",
"149\\101\\207\\0\\",
"149\\101\\192\\0\\",
"149\\101\\180\\0\\",
"149\\101\\17\\0\\",
"149\\101\\164\\0\\",
"149\\101\\160\\0\\",
"149\\101\\150\\0\\",
"149\\101\\128\\0\\",
"149\\101\\127\\0\\",
"149\\101\\118\\0\\",
"149\\101\\111\\0\\",
"149\\101\\107\\0\\",
"149\\101\\103\\0\\",
"149\\101\\102\\0\\",
"149\\101\\101\\0\\",
"149\\101\\100\\0\\",
"149\\101\\1\\0\\",
"147\\49\\0\\0\\",
"159\\64\\0\\0\\",
"159\\158\\0\\0\\",
"158\\74\\54\\0\\",
"158\\74\\38\\0\\",
"158\\74\\0\\0\\",
"158\\73\\196\\0\\",
"158\\73\\0\\0\\",
"158\\72\\139\\0\\",
"158\\72\\0\\0\\",
"158\\71\\192\\0\\",
"158\\71\\192\\0\\",
"158\\71\\128\\0\\",
"158\\71\\0\\0\\",
"158\\70\\9\\0\\",
"158\\70\\8\\0\\",
"158\\70\\8\\0\\",
"158\\70\\43\\0\\",
"158\\70\\42\\0\\",
"158\\70\\41\\0\\",
"158\\70\\40\\0\\",
"158\\70\\39\\0\\",
"158\\70\\38\\0\\",
"158\\70\\37\\0\\",
"158\\70\\36\\0\\",
"158\\70\\35\\0\\",
"158\\70\\34\\0\\",
"158\\70\\33\\0\\",
"158\\70\\32\\0\\",
"158\\70\\29\\0\\",
"158\\70\\28\\0\\",
"158\\70\\28\\0\\",
"158\\70\\27\\0\\",
"158\\70\\26\\0\\",
"158\\70\\25\\0\\",
"158\\70\\24\\0\\",
"158\\70\\21\\0\\",
"158\\70\\20\\0\\",
"158\\70\\19\\0\\",
"158\\70\\18\\0\\",
"158\\70\\174\\0\\",
"158\\70\\15\\0\\",
"158\\70\\147\\0\\",
"158\\70\\146\\0\\",
"158\\70\\146\\0\\",
"158\\70\\144\\0\\",
"158\\70\\14\\0\\",
"158\\70\\139\\0\\",
"158\\70\\138\\0\\",
"158\\70\\137\\0\\",
"158\\70\\136\\0\\",
"158\\70\\135\\0\\",
"158\\70\\134\\0\\",
"158\\70\\133\\0\\",
"158\\70\\132\\0\\",
"158\\70\\131\\0\\",
"158\\70\\130\\0\\",
"158\\70\\13\\0\\",
"158\\70\\129\\0\\",
"158\\70\\128\\0\\",
"158\\70\\12\\0\\",
"158\\70\\113\\0\\",
"158\\70\\112\\0\\",
"158\\70\\11\\0\\",
"158\\70\\10\\0\\",
"158\\70\\0\\0\\",
"162\\99\\192\\0",
	"50.\\.7\\.49\\.4"
]

domains=[
    "(.*.gov)",
	"(.*.gov.uk)",
	"gov\\.uk",
	"(.*google.com)",
	"(.*google.co.uk)",
	"(.*discord.com)",
	"(.*discordapp.com)",
	"(.*github.com)",
	"(.*github.io)",
]