[white]
colors=[
    [255,255,255]
]

[slovakia]
colors=[
    [255,255,255],
    [52,158,235],
    [255,0,0]
]

[mew]
colors=[
    [255,182,193],
    [216,191,216],
    [150,222,209]
]
