[standard]
theme="default"
maxtime=120
cooldown=120
concurrents=1
roles=[]
days=30
daily_attacks=0

[standard_pro]
theme="default"
maxtime=200
cooldown=60
concurrents=2
roles=[]
days=30
daily_attacks=0

[standard_max]
theme="default"
maxtime=500
cooldown=60
concurrents=4
roles=[]
days=30
daily_attacks=0

[vip]
theme="default"
maxtime=1200
cooldown=30
concurrents=4
roles=["vip"]
days=30
daily_attacks=0

[reseller]
theme="default"
maxtime=1200
cooldown=30
concurrents=4
roles=["reseller"]
days=30
daily_attacks=0